# Generated by Django 5.2.6 on 2025-09-29 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GraficaReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('infraccion', 'Infracción'), ('infraestructura', 'Infraestructura'), ('residuo', 'Residuo especial'), ('general', 'General')], max_length=20)),
                ('periodo', models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual')], max_length=10)),
                ('datos', models.JSONField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graficas_reporte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'graficas_reporte',
                'indexes': [models.Index(fields=['tipo_reporte'], name='graficas_re_tipo_re_10178d_idx'), models.Index(fields=['periodo'], name='graficas_re_periodo_a99b93_idx')],
            },
        ),
    ]
