# Generated by Django 5.2.6 on 2025-09-29 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('infraccion', 'Infracción'), ('danos', 'Daño a la infraestructura'), ('residuo', 'Residuo especial')], max_length=50)),
                ('tipo_estructura', models.CharField(blank=True, choices=[('Alcantarillado', 'Alcantarillado'), ('Acueducto', 'Acueducto')], max_length=20, null=True)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('Enviado', 'Enviado'), ('En proceso', 'En proceso'), ('Finalizado', 'Finalizado'), ('Rechazado', 'Rechazado')], db_index=True, default='Enviado', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('anonimo', models.BooleanField(default=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='reportes/%Y/%m/%d/')),
                ('ciudadano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reportes',
                'indexes': [models.Index(fields=['estado'], name='reportes_estado_7afa2e_idx'), models.Index(fields=['tipo_reporte'], name='reportes_tipo_re_d41df6_idx')],
            },
        ),
    ]
