# Generated by Django 5.2.6 on 2025-09-29 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('infraccion', 'Infracción'), ('danos', 'Infraestructura'), ('residuo', 'Residuo especial')], max_length=20)),
                ('puntaje', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('evaluado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('evaluador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to='reportes.reporte')),
            ],
            options={
                'db_table': 'evaluaciones',
                'indexes': [models.Index(fields=['tipo_reporte'], name='evaluacione_tipo_re_e1f541_idx'), models.Index(fields=['puntaje'], name='evaluacione_puntaje_3f2138_idx'), models.Index(fields=['fecha_evaluacion'], name='evaluacione_fecha_e_4601e8_idx')],
            },
        ),
    ]
